# Generated by Django 5.0 on 2024-02-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GenderDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=20)),
                ("distribution", models.FloatField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insight_app.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Territory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(help_text="Full Country name", max_length=100),
                ),
                ("distribution", models.CharField(max_length=3)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insight_app.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TotalByDay",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("video_views", models.IntegerField()),
                ("profile_views", models.IntegerField()),
                ("likes", models.IntegerField()),
                ("comments", models.IntegerField()),
                ("shares", models.IntegerField()),
                ("unique_viewers", models.IntegerField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insight_app.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TotalFollowers",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
                ("followers", models.IntegerField(blank=True, null=True)),
                ("difference", models.IntegerField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insight_app.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("time", models.DateTimeField()),
                ("video_title", models.CharField(max_length=255)),
                ("video_link", models.URLField(max_length=500)),
                ("post_time", models.DateTimeField(primary_key=True, serialize=False)),
                ("video_views_within_7_days", models.IntegerField()),
                ("total_likes", models.IntegerField()),
                ("total_comments", models.IntegerField()),
                ("total_shares", models.IntegerField()),
                ("total_views", models.IntegerField()),
                ("tags", models.TextField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insight_app.report",
                    ),
                ),
            ],
        ),
    ]
