# Generated by Django 5.0 on 2024-02-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="territory",
            name="distribution",
            field=models.FloatField(),
        ),
    ]
