# Generated by Django 5.0 on 2024-02-12 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insight_app", "0002_alter_territory_distribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowersActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("hour", models.IntegerField()),
                ("active_followers", models.IntegerField()),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insight_app.report",
                    ),
                ),
            ],
        ),
    ]
